language: node_js
node_js:
- 9
- 8
- 7
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - yarn dev
  - yarn lint
notifications:
  slack:
    on_success: change
    secure: sUFsLohv9uZRn9zEXnAQM3nQ8v1Af10k/coafDZ8bMDWnbGtDDGZokDpi4V5vfYImNpa74m1p4OyF2zyMY0x3gwRKwpcXamFDEU40y1itCKIapLiHe16GjDY9qMXnxwVOWgg1GHqiEJCR52yusTtfcv0O/aB9diVUezDKV2ZLs0v5ctP+pzbB+iFn2xyJfgm3+NoT9qEhQPAacNi1onWhkeE5Hm2XtV+kDx2qVDWHd1W/0VR0h7d3Du4NFbRVCGYGupAqfwrggzimc2kY8vbSFyHGiYoy4JBzvd3bQVkcRNxdln/VK+osDuN8SMl5xpQrlMn3LoPY2DIznUzUuIy7B+UEhbijHfGTEJTxl2LK2jXty9hPuiu1FG1E3aivHNY5YarmL6qP3GWJYT3ZTGrMqb4EQ/K3/d22sX7BvK9WfScT4qlOT51g96arv0+n0YlsQ2/fvThzbSBpd540lQxxIZUuHYuOU3pAFB5Cp3cIvdzhes4k8wo2pYHU9TuHHLTEAeLu7kPWAaFs4hbxz0o9T4WKWoX7kRL4Mdan4EKWi85DctJhx/a2fItAKQxL6Vqvo7TUY1q3hS3VBl6dNwC0uxox0hTK6Q9qnd+yCF2pZWXlJppaIa2e1+l764xwCFRycA4o40VFL8rx7bo6+eo8IgLGFEjC1IPY+2pveHpp0I=
